# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'TheARM' do
pod "AFNetworking", "~> 3.0"
pod "MBProgressHUD", "~> 1.0.0"
pod 'iOS-Slide-Menu', "~> 1.5"
end

